### ISSUE TITLE
Illegally formed thumbnails

### ISSUE THREAD

**Issue by gynter** [themes-jekyll/themes-jekyll.github.io#10]
Wrong aspect ratio (stretched in or outwards):
- ~~Vanilla Bean Creme~~
- ~~Green Tea~~
- ~~Left~~
- ~~Minimal Mistakes~~
- ~~Kasper~~
- ~~Simply Grey~~
- ~~brume~~
- ~~Bitwiser~~
- ~~Clean Blog~~
- ~~Freshman21~~
- ~~Carte Noire~~
- ~~Polar Bear~~
- ~~Arctic Fox~~
- ~~{ Personal }~~
- ~~Jekyll Material Design Lite~~
- ~~Mickey~~
- ~~Carte~~
- ~~Book~~

**Comment by mushishi78** [comment]
I had a go at replacing these: [Replacement Thumbnails](https://github.com/jekyllrc/jekyllthemes/commit/267cfb1c9af17f1f36610acfd34f72690efbca1f)

**Comment by gynter** [comment]
@mushishi78 Thanks, good job! I stroke trough the ones which seems fine to me. The one which seems completely wrong for me is now Left, the previous one was correct, but with wrong aspect ratio. Check its [demo](http://zachholman.com/left/) page.

**Comment by jacobtomlinson** [comment]
Yeah it looks like you took a screenshot of @holman's article about left and not left itself. Although perhaps he could weigh in and say which is correct.

**Comment by mushishi78** [comment]
Sorry, I clicked on the Left demo's first post and just assumed that was part of the theme. If it's not, we should probably fork the project and provide a demo that's more representative.

I've replaced the thumbnail now with the image from the README.

**Comment by gynter** [comment]
Nice, I'll leave this issue open, maybe someone find more of those.
