### ISSUE TITLE
Add Piwik analytics

### ISSUE THREAD

**Issue by gynter** [themes-jekyll/themes-jekyll.github.io#12]
@jekyllrc/themes since I'm not a fan of Google spyware products like Google Analytics then are You fine when I'll add this page to my [Piwik](http://piwik.org/) set-up (https://www.kits.ee/analytics/) so I can get some analytics about the page?

The disadvantage is that I can't add You access to the analytics, but maybe I can produce monthly reports somehow (not sure at the moment, if there are built-in functions for that).

**Comment by mushishi78** [comment]
:+1:

**Comment by gynter** [comment]
Ok, done.
