### ISSUE TITLE
Domain name proposition: themes.jekyllrc.org

### ISSUE THREAD

**Issue by gynter** [themes-jekyll/themes-jekyll.github.io#3]
Hei!

I have registered jekyllrc.org domain. What do You think about serving this repository from themes.jekyllrc.org?

Günter.

/cc @jekyllrc/themes

**Comment by mushishi78** [comment]
:+1:

**Comment by erlend-sh** [comment]
:+1:

**Comment by RizRiyz** [comment]
btw themes.jekyllrc.org will be themes database and what about the rest of domain? I mean jekyllrc.org

**Comment by gynter** [comment]
No clue yet, maybe some placeholder page.

Added CNAME file for themes.jekyllrc.org.

**Comment by erlend-sh** [comment]
Just redirect jekyllrc.org to themes.jekyllrc.org for now?

**Comment by gynter** [comment]
I don't know if this is a good idea, might cause issues with SEO later. I'll put some placeholder there.

**Comment by erlend-sh** [comment]
Sure. Here's a placeholder image you can use :stuck_out_tongue: 

https://openclipart.org/detail/178586/mad-scientist
https://openclipart.org/detail/190942/mad-scientist

**Comment by gynter** [comment]
Heh, nice! @erlend-sh can You provide me SVG's of those? I'm unable to convert them successfully on my linux machine (Windows no avail).

**Comment by erlend-sh** [comment]
Isn't that what you get if you press the big red download button?

**Comment by gynter** [comment]
Lolwat, sorry, I'm blind ;) Didn't realize that it was a button :smile:
