### ISSUE TITLE
Demo pages

### ISSUE THREAD

**Issue by gynter** [themes-jekyll/themes-jekyll.github.io#5]
@mushishi78 Is the https://github.com/jekyll-demos project created by You? What would you think about an idea to create a repository called jekyllthemes-demos and link all those as submodules?

Pros:
- all in one repo;
- we can use existing teams workflow, therefore can give Themes team access to it;
- easier to update;
- we can serve those via demos.jekyllrc.org domain;
- one less organization to manage.

Cons:
- must manually build all pages (but can be fully automated using a simple unix makefile and Jenkins).

**Comment by gynter** [comment]
Done.

**Comment by jacobtomlinson** [comment]
If we're going for a manual build I would recommend using Travis CI as that allows good transparency and lots of people are familiar with it in open source projects. Also as Jekyll is ruby then we should use a Rakefile. 

However I strongly encourage to stick to a pure GitHub Pages build solution, it makes it easier to understand that this is a website about Jekyll created using Jekyll.

**Comment by mushishi78** [comment]
Yeah I did all the jekyll-demos, I thought it wise not to clutter an useful organisation with all those repos.

I'm not sure I understand. Surely all the team would have access to change is where the submodules point, they couldn't actually maintain the jekyll projects, could they?

Either way, it should be needless to say that I'm happy giving away the admin access to the jekyll-demos organisation if that helps at all.

**Comment by gynter** [comment]
No, the access is not the issue. My idea was to create one repo, then link all of those themes, which are in Github as submodules, and those which are not, but are missing we can commit to that repo manually, this gives us a one unified way to present demos if those are missing.

**Comment by gynter** [comment]
Maybe easiest way to explain is that I create an example? I can do it later, at the evening.

**Comment by mushishi78** [comment]
tbh I don't really understand how submodules work, so I'm probably the source of confusion.

Would this mean that every time a new project is added, a maintainer then has to add that project as a submodule to the demos repo?
