### ISSUE TITLE
Images are pixelated

### ISSUE THREAD

**Issue by daattali** [themes-jekyll/themes-jekyll.github.io#7]
In the old jekyllthemes website, images were 200x250. In this version, the size has been increased, but since the image files themselves are 200x250, they all look pixelated.  I'm not sure what the solution should be, just raising the issue.

Perhaps the instructions on the new site should be updated to use the new dimensions rather than 200x250, so that any NEW submissions will at least benefit from that

**Comment by mushishi78** [comment]
Thanks for reporting. We're trying to sort that out on this pull request: [Higher Res Images](https://github.com/jekyllrc/jekyllthemes/pull/2)

**Comment by daattali** [comment]
Ah, wasn't looking in the PRs.  Very nice, good work :+1:
